
CREATE TABLE [dbo].[GenericEntity](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[JobId] [bigint] NOT NULL,
	[CountryISO2A] [varchar](2) NOT NULL,
	[StrColumn1] [varchar](50) NULL,
	[StrColumn2] [varchar](50) NULL,
	[StrColumn3] [varchar](50) NULL,
	[StrColumn4] [varchar](50) NULL,
	[StrColumn5] [varchar](50) NULL,
	[StrColumn6] [varchar](50) NULL,
	[StrColumn7] [varchar](50) NULL,
	[StrColumn8] [varchar](50) NULL,
	[StrColumn9] [varchar](50) NULL,
	[StrColumn10] [varchar](50) NULL,
	[IntColumn1] [int] NULL,
	[IntColumn2] [int] NULL,
	[IntColumn3] [int] NULL,
	[IntColumn4] [int] NULL,
	[IntColumn5] [int] NULL,
	[IntColumn6] [int] NULL,
	[IntColumn7] [int] NULL,
	[IntColumn8] [int] NULL,
	[IntColumn9] [int] NULL,
	[IntColumn10] [int] NULL,
	[BoolColumn1] [bit] NULL,
	[BoolColumn2] [bit] NULL,
	[BoolColumn3] [bit] NULL,
	[BoolColumn4] [bit] NULL,
	[BoolColumn5] [bit] NULL,
	[BoolColumn6] [bit] NULL,
	[BoolColumn7] [bit] NULL,
	[BoolColumn8] [bit] NULL,
	[BoolColumn9] [bit] NULL,
	[BoolColumn10] [bit] NULL,
	[DateColumn1] [datetime] NULL,
	[DateColumn2] [datetime] NULL,
	[DateColumn3] [datetime] NULL,
	[DateColumn4] [datetime] NULL,
	[DateColumn5] [datetime] NULL,
	[DateColumn6] [datetime] NULL,
	[DateColumn7] [datetime] NULL,
	[DateColumn8] [datetime] NULL,
	[DateColumn9] [datetime] NULL,
	[DateColumn10] [datetime] NULL,
	[FloatColumn1] [float] NULL,
	[FloatColumn2] [float] NULL,
	[FloatColumn3] [float] NULL,
	[FloatColumn4] [float] NULL,
	[FloatColumn5] [float] NULL,
	[FloatColumn6] [float] NULL,
	[FloatColumn7] [float] NULL,
	[FloatColumn8] [float] NULL,
	[FloatColumn9] [float] NULL,
	[FloatColumn10] [float] NULL,
	[CreationTimeStamp] [datetime] NULL,
 CONSTRAINT [PK_GenericEntity] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

