CREATE TABLE [dbo].[PanelTableTypeDummy](
		[Rownumber] [int] NULL,
		[PanelCode] [int] NULL,
		[GroupRoleCode] [nvarchar](100) NULL,
		[PanelRoleCode] [nvarchar](100) NULL,
		[PanelistStateCode] [nvarchar](100) NULL,
		[PanelistCommunicationMethodology] [nvarchar](100) NULL,
		[PanelistCommunicationMethodologyChangeReason] [nvarchar](max) NULL,
		[PanelistCommunicationMethodologyChangeComment] [nvarchar](max) NULL,
		[AddressLine1] [nvarchar](200) NULL,
		[AddressLine2] [nvarchar](200) NULL,
		[AddressLine3] [nvarchar](200) NULL,
		[AddressLine4] [nvarchar](200) NULL,
		[PostCode] [nvarchar](100) NULL,
		[AddressType] [nvarchar](200) NULL,
		[Order] [int] NULL,
		[HomePhone] [nvarchar](200) NULL,
		[WorkPhone] [nvarchar](200) NULL,
		[MobilePhone] [nvarchar](200) NULL,
		[PhoneOrder] [int] NULL,
		[PhoneType] [nvarchar](200) NULL,
		[Phone] [nvarchar](200) NULL,		
		[EmailOrder] INT,
		[EmailType] NVARCHAR (200)  NULL,
		[Email] NVARCHAR (200)  NULL,
		[fileid] [NVARCHAR](500),
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]