CREATE TYPE [dbo].[ImportFeed1] AS TABLE (
    [Rownumber]                         INT             NULL,
    [FirstName]                         NVARCHAR (300)  NULL,
    [MiddleName]                        NVARCHAR (300)  NULL,
    [LastName]                          NVARCHAR (300)  NULL,
    [EmailAddress]                      NVARCHAR (200)  NULL,
    [HomeAddressLine1]                  NVARCHAR (200)  NULL,
    [HomeAddressLine2]                  NVARCHAR (200)  NULL,
    [HomeAddressLine3]                  NVARCHAR (200)  NULL,
    [HomeAddressLine4]                  NVARCHAR (200)  NULL,
    [HomePostCode]                      NVARCHAR (100)  NULL,
    [DateOfBirth]                       DATETIME        NULL,
    [EnrollmentDate]                    DATETIME        NULL,
    [Sex]                               INT             NULL,
    [Title]                             INT             NULL,
    [GroupMembershipStateCode]          NVARCHAR (100)  NULL,
    [SupportCharity]                    BIT             NULL,
    [NonParticipant]                    BIT             NULL,
    [FrecuencyValue]                    NVARCHAR (1000) NULL,
    [NextEvent]                         DATETIME        NULL,
    [AmountValue]                       INT             NULL,
    [GroupId]                           NVARCHAR (100)  NULL,
    [CommunicationIncoming]             INT				NULL,
    [CommunicationContactMechanismCode] INT             NULL,
    [CommunicationCommReasonType]       INT             NULL,
    [Alias]                             NVARCHAR (300)  NULL,
    [Comments]                          NVARCHAR (1000) NULL,
    [CommunicationCreationDateTime]     DATETIME        NULL,
    [IndividualAlias]                   VARCHAR (100)   NULL,
    [BusinessId]                        VARCHAR (100)   NULL,
	[FullRow]							NVARCHAR (MAX) NULL,
	[GACode]                            NVARCHAR (100)  NULL);

