CREATE PROCEDURE [dbo].[GetPanelTaskTypes] (
	@pCountryId UNIQUEIDENTIFIER
	,@pCultureCode INT
	)
AS
BEGIN
	SELECT DISTINCT SPT.SurveyParticipationTaskId AS [PanelTaskId]
		,TT.VALUE AS [TaskType]
		,SPT.PanelTaskType_Id AS [PanelTaskTypeId]
	FROM SurveyParticipationTask SPT
	JOIN PanelSurveyParticipationTask PSPT ON SPT.SurveyParticipationTaskId = PSPT.Task_Id
	LEFT JOIN PANELTASKTYPE PTT ON SPT.PANELTASKTYPE_ID = PTT.GUIDREFERENCE
	LEFT JOIN TRANSLATION T ON T.TRANSLATIONID = PTT.[DESCRIPTION_Id]
	LEFT JOIN TRANSLATIONTERM TT ON T.TRANSLATIONID = TT.TRANSLATION_ID
	WHERE PSPT.COUNTRY_ID = @pCountryId
		AND TT.CULTURECODE = @pCultureCode
END
